### ISSUE TITLE
Galaxy size options aren't loading in Stellaris GamePass

### ISSUE THREAD

**Issue by M109A6** [hmlendea/stellaris-ui-galaxy-sizes#11]
I've been trying to get the galaxy sizes mod to load but, it doesn't matter which order I load the mods, or the mod by itself, I can't get the galaxy size options to change when starting a new game.

Below test conducted with only Universum Infinitum enabled.
[Galaxy Size Screenshot](https://i.imgur.com/VMZbaDN.mp4 )

**Comment by hmlendea** [comment]
Solved by #12 Thanks for the report
